const fs=require('fs'),vm=require('vm'),assert=require('assert'),{createCanvas}=require('@napi-rs/canvas');
const canvas=createCanvas(360,780);canvas.addEventListener=()=>{};canvas.getBoundingClientRect=()=>({left:0,top:0,width:360,height:780});
const math=Object.create(Math);math.random=()=>0;
const sandbox={Math:math,Set,Map,window:{devicePixelRatio:1,addEventListener(){},setTimeout(){}},document:{getElementById:()=>canvas,createElement:()=>createCanvas(1,1),addEventListener(){}},navigator:{},location:{protocol:'file:'},localStorage:{getItem:()=>null,setItem(){}},requestAnimationFrame(){}};
let source=fs.readFileSync(require('path').join(__dirname,'../game.js'),'utf8').replace(/\}\)\(\);\s*$/,`globalThis.g={beginGame,startStage,update,pauseGame,resumeGame,specialBurst,drawSpecials,drawSpecialButton,drawItems,specialDropRules,trySpecialDrop,pointerDown,pointerUp,fireSpecial,resize,loseLife,captureFighter,updateShieldContacts,updateSpecials,drawShield,drawControls,shootPlayer,updatePlasmaGuidance,continueGame,get:()=>({shieldTime,weapon,lives,enemies,enemyShots,playerShots,boss,H,items,specialAmmo,specialDropTimer,specialFields,specialShots,specialCooldown,specialButtons,joy,fireButton,ship}),setStage:n=>{stage=n;startStage()},ammo:a=>specialAmmo=a,setWeapon:n=>weapon=n,dual:()=>dualFighter=true,fire:()=>{keys.add(' ');fireCooldown=0}};})();`);
vm.runInNewContext(source,sandbox);const g=sandbox.g;
g.beginGame();g.setStage(41);let s=g.get();assert.equal(s.specialButtons.length,3);
for(const b of s.specialButtons){assert(b.y+26<=s.H);for(const c of [s.joy,s.fireButton])assert(Math.hypot(b.x-c.x,b.y-c.y)>74);for(const c of s.specialButtons)if(c!==b)assert(Math.hypot(b.x-c.x,b.y-c.y)>52);}
// Keep existing drop chance and use exactly 20% of successful drops for the shield.
const enemy={x:100,y:180};for(const [stage,roll,type] of [[40,0,'emp'],[41,0,'shield'],[41,.1999,'shield'],[41,.2,'emp'],[41,.5999,'emp'],[41,.6,'flash']]){g.beginGame();g.setStage(stage);let n=0;math.random=()=>n++===0?0:roll;g.trySpecialDrop(enemy);assert.equal(g.get().items[0].type,type);}
g.beginGame();g.setStage(41);g.get().items.push({type:'shield',x:g.get().ship.x,y:g.get().ship.y,vy:0});g.update(.001);assert.equal(g.get().specialAmmo.join(','),'shield');g.ammo(['shield','emp']);g.trySpecialDrop(enemy);assert.equal(g.get().items.length,0,'total capacity two');
const button=g.get().specialButtons.find(b=>b.type==='shield');g.pointerDown({clientX:button.x,clientY:button.y,pointerId:4,preventDefault(){}});assert.equal(g.get().shieldTime,3);assert.equal(g.get().specialShots.length,0,'instant personal shield');assert.equal(g.get().specialAmmo.join(','),'emp');
s=g.get();s.ship.invulnerable=0;for(const type of ['straight','spread','homing','wave'])s.enemyShots.push({x:s.ship.x,y:s.ship.y,type,r:3});const e=s.enemies.find(e=>e.role!=='captor');e.x=s.ship.x;e.y=s.ship.y;e.entry=null;const life=s.lives;g.loseLife();assert.equal(g.get().lives,life);g.captureFighter(s.enemies.find(e=>e.role==='captor'));assert.equal(g.get().lives,life);g.updateShieldContacts();assert.equal(g.get().enemyShots.length,0);assert(!e.alive,'contact destroys even armored normal enemies');g.pauseGame();g.update(1);assert.equal(g.get().shieldTime,3,'pause freezes protection');g.resumeGame();g.updateSpecials(2.99);assert(g.get().shieldTime>0);g.updateSpecials(.02);assert.equal(g.get().shieldTime,0);g.get().ship.invulnerable=0;g.loseLife();assert.equal(g.get().lives,life-1,'damage resumes on expiry');
// Bosses survive contact, and repeated frames cannot multiply contact damage.
g.beginGame();g.setStage(50);g.ammo(['shield']);g.fireSpecial('shield');s=g.get();s.boss.x=s.ship.x;s.boss.y=s.ship.y;const hp=s.boss.hp;g.updateShieldContacts();assert.equal(g.get().boss.hp,hp-3);g.updateShieldContacts();assert.equal(g.get().boss.hp,hp-3);g.updateSpecials(.5);g.updateShieldContacts();assert.equal(g.get().boss.hp,hp-6);
for(const level of [7,8]){g.beginGame();g.setWeapon(level);g.get().ship.invulnerable=999;g.fire();g.update(.001);assert.equal(g.get().specialCooldown,0);const n=g.get().playerShots.length;g.update(.37);assert.equal(g.get().playerShots.length,n);g.update(.011);assert.equal(g.get().playerShots.length,n+1,'.38 cadence');}
let shots=[];for(const level of [6,8]){g.beginGame();g.setWeapon(level);s=g.get();s.enemies.length=0;s.enemies.push({x:s.ship.x+90,y:s.ship.y-220,alive:true});g.shootPlayer();let shot=s.playerShots.at(-1);g.updatePlasmaGuidance(shot,.1);shots.push(shot);assert(shot.vy<0);assert.equal(shot.trackingTime,level===8?1.1:.9);g.updatePlasmaGuidance(shot,.85);assert.equal(shot.guidanceEnded,level===6);}
assert(Math.abs(Math.atan2(shots[1].vx,-shots[1].vy))>Math.abs(Math.atan2(shots[0].vx,-shots[0].vy)),'stronger but bounded steering');
g.beginGame();g.setStage(41);g.ammo(['shield','emp']);g.fireSpecial('shield');const ctx=canvas.getContext('2d');ctx.fillStyle='#07101a';ctx.fillRect(0,0,360,780);g.drawShield();g.drawControls();g.drawSpecialButton();fs.writeFileSync('/tmp/v31-shield-controls.png',canvas.toBuffer('image/png'));g.beginGame();assert.equal(g.get().shieldTime,0,'fresh game clears protection');
console.log('PASS: separated three buttons, stage41 shield drop/pickup/20% share/cap, instant 3s shield, bullet/collision/capture protection, pause/expiry/reset, boss damage cap, stage70 cadence/stage80 guidance and native shield artwork');
